[tools]
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bottom = "latest"
delta = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
jq = "latest"
kubectl = "latest"
lazygit = "latest"
node = "latest"
rg = "latest"
ruff = "latest"
terraform = "latest"
uv = "latest"
zoxide = "latest"
hyperfine = "latest"
terraform-ls = "latest"
